language: cpp
compiler:
  - gcc
before_script:
 - sudo apt-get install libgmp3-dev libboost-thread-dev libboost-regex-dev libboost-system-dev libboost-filesystem-dev liblua5.1-dev libxml2-dev libsqlite3-dev libmysqlclient-dev
script: |
  cmake -DUSE_MYSQL=On -DUSE_SQLITE=On .
  make
notifications:
  irc:
#    - "irc.quakenet.org#otserv"
